=== czchen/iclang/schema/hyperscript-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "ICLang HyperScript JSON Schema",
    "type": "object",
    "required":["properties", "processes", "connections"],
    "properties": {
        "comment": {"$ref":"#/difinitions/comment"},
        "properties": {"$ref":"#/difinitions/properties"},
        "processes": {"$ref":"#/difinitions/processes"},
        "connections": {"$ref":"#/difinitions/connections"},
        "inports": {"$ref":"#/difinitions/inports"},
        "exports": {"$ref":"#/difinitions/exports"}
    },
    "difinitions":{        
        "properties":{
            "type":"object",
            "properties":{
                "name":{
                    "type":"string",
                    "required": true
                },
                "description":{
                    "type":"string",
                    "required": true
                }
            }
        },
        "processes":{
            "type":"object"
        },
        "connections":{
            "type":"array",
            "items":{
                "type":"object",
                "required": ["src", "dest"],
                "properties":{
                    "src":{},
                    "dest":{}
                }
            }
        },
        "inports":{
            "type":"array"
        },
        "exports":{
            "type":"array"
        },
        "comment":{
            "type":"string"
        }        
    }
}

=== czchen/iclang/example/simple-hyperscript.json
{
    "properties":{
        "name":"read a string and print",
        "description": "read a string then print it to console."
    },
    "processes":{
        "Read":{
            "component":"ReadComponentId"
        },
        "Print":{
            "component":"PrintComponentId"
        }
    },
    "connections":[
        {
            "src":{
                "process":"Read",
                "port":"out"                
            },
            "dest":{
                "process":"Print",
                "port":"in"
            }
        }
    ],
    "inports":[
        {
            "name":"str",          
            "dest":{
                "process":"Read",
                "port":"in"
            }
        }
    ],
    "exports":[
        {
            "name":"status",
            "src":{
                "process":"Print",
                "port":"out"
            }
        }    
    ]
}
